CREATE TABLE TRANSACTIONS(
    id BIGINT NOT NULL AUTO_INCREMENT,
    payer_id BIGINT NOT NULL,
    payee_id BIGINT NOT NULL,
    amount DECIMAL(15, 2),
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY(id),
    CONSTRAINT fk_payer FOREIGN KEY (payer_id) REFERENCES USERS(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payee FOREIGN KEY (payee_id) REFERENCES USERS(id) ON DELETE RESTRICT
)