services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root