services:
  server:
    build: .
    entrypoint: wait-for db:3306 -t 40 -- ./app/.docker/entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root